service: serverless-typescript
plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-plugin-warmup
custom:
  warmup:
    default:
      enabled: true # Whether to warm up functions by default or not
      folderName: '.warmup' # Name of the folder created for the generated warmup 
      events:
        - schedule: cron(0/5 0-1 ? * MON-FRI *)
      concurrency: 5

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: ap-northeast-2

functions:
  hello:
    handler: src/handler.hello
    events:
      - http:
          path: hello
          method: get
    warmup:
      default:
        clientContext:
          source: different-source-only-for-this-lambda
        payload:
          source: different-source-only-for-this-lambda
        concurrency: 5